/* TEMP FIX */
#include "non_matchings.hpp"

GLOBAL_ASM("data/dsp.data.s")
GLOBAL_ASM("data/dsp.rodata.s")

GLOBAL_ASM("asm/_ZN2nn3dsp3CTR17IsComponentLoadedEv.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR15UnloadComponentEv.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR21SetSemaphoreEventMaskEt.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR6WakeUpEv.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR23GetSemaphoreEventHandleEPNS_6HandleE.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR23RegisterInterruptEventsENS_6HandleEii.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR22OrderToWaitForFinalizeEv.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR10InitializeEv.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR5AwakeEv.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR18GetHeadphoneStatusEPb.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR27RegisterSleepWakeUpCallbackEPFvvES3_S3_.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR12SetSemaphoreEt.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR32ConvertProcessAddressFromDspDramEjPj.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR16WriteProcessPipeEiPKhj.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR8RecvDataEtPt.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR18ReadPipeIfPossibleEiPhtPt.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR15RecvDataIsReadyEtPb.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR5SleepEv.s")
GLOBAL_ASM("asm/_ZN2nn3dsp3CTR14FlushDataCacheEjj.s")
